version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.firebase:firebase-database
    versions:
    - 19.6.0
  - dependency-name: com.google.firebase:firebase-messaging
    versions:
    - 21.0.1
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - 1.4.2-native-mt
